# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'devops-aks'
  aksResourceGroup: 'saxrg'
  aksClusterName: 'saxcluster'

steps:
- task: Kubernetes@1
  displayName: 'Connect to AKS and List Nodes'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'devops-aks'    # your K8s service connection
    namespace: 'default'
    command: 'get'
    arguments: 'nodes'
