# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'aks-sp'
  aksResourceGroup: 'saxrg'
  aksClusterName: 'saxcluster'

steps:
- script: |
    echo "Fetching public IP address of the Microsoft-hosted agent..."
    curl ifconfig.me
  displayName: Get Agent Public IP2
  
- task: AzureCLI@2
  displayName: Connect to AKS (admin) & List Nodes
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logging into AKS cluster as cluster-admin..."
      az aks get-credentials \
        --resource-group $(aksResourceGroup) \
        --name $(aksClusterName) \
        --overwrite-existing \
        --admin

      echo "Verifying node list:"
      kubectl get nodes

- script: |
    echo "Fetching public IP address of the Microsoft-hosted agent..."
    curl ifconfig.me
  displayName: Get Agent Public IP

